libs =

if $config.cxxopts.use_unicode
  import libs += libicuuc%lib{icuuc}

./: lib{cxxopts}: hxx{cxxopts} $libs
{
  cxx.export.poptions = "-I$src_base"
  cxx.export.libs = $libs
}

if $config.cxxopts.use_unicode
  lib{cxxopts}: cxx.export.poptions += -DCXXOPTS_USE_UNICODE

hxx{cxxopts}@./: install = include/
